name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_OPENAI_API_KEY: ${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Run validation
      run: npm run validate
      
    - name: Deploy to Firebase App Hosting
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      run: |
        npm install -g firebase-tools
        firebase apphosting:backends:create cgg-be --location=europe-west4 --token "$FIREBASE_CI_TOKEN" || true
        firebase deploy --only apphosting --token "$FIREBASE_CI_TOKEN"
      env:
        FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
        
    - name: Deploy to Firebase (Preview)
      if: github.event_name == 'pull_request'
      run: |
        npm install -g firebase-tools
        firebase apphosting:backends:create cgg-be-preview-${{ github.event.number }} --location=europe-west4 --token "$FIREBASE_CI_TOKEN" || true
        firebase apphosting:backends:deploy cgg-be-preview-${{ github.event.number }} --token "$FIREBASE_CI_TOKEN"
      env:
        FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
